#! /bin/sh
# /etc/init.d/fermentation-web

### BEGIN INIT INFO
# Provides:          fermentation-web
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / st$
### END INIT INFO

# 1) Make script executable:
# sudo chmod 755 /etc/init.d/fermentation-web

# 2) Register script to be run at start-up:
# sudo update-rc.d fermentation-web defaults

# To remove script from start-up:
# sudo update-rc.d -f fermentation-web remove

# To test starting the program:
# sudo /etc/init.d/fermentation-web start

# To test stopping the program:
# sudo /etc/init.d/fermentation-web stop

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
    start)
        echo "Starting Fermentation Web"
        # run application you want to start
        python /mnt/scripts/Brewery/Fermentation_WebApp.py
    ;;
    stop)
        echo "Stopping Fermentation Web"
        # kill application you want to stop
        killall python
    ;;
*)
    echo "Usage: /etc/init.d/fermentation-web {start|stop}"
    exit 1
    ;;
esac

exit 0
